### ISSUE TITLE
Package Visual C++ redistribution files into the installer

### ISSUE THREAD

**Issue by mitchazj** [mitchazj/truffle#13]
Otherwise, if no C++ redistribution package is available on the host PC, Black-Sink refuses to run.

**Comment by amaitland** [comment]
For reference you can include the `VC++` runtime files without actually having to install the runtime.

https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#6-how-do-i-include-the-visual-studio-c-20122013-redistributables-on-the-target-app

**Comment by mitchazj** [comment]
Awesome, thanks!

**Comment by mitchazj** [comment]
Latest installer includes these binaries, will be publicly released soon.
