### ISSUE TITLE
Audio file playing on sync

### ISSUE THREAD

**Issue by Wade-Jensen** [mitchazj/truffle#2]
When I restart my computer, if Black-Sink performs a sync, it will reproducibly play an audio file within its directories.

Quite comically, this is the first 8 seconds of the Pink Panther theme which is in the files for a signals processing subject. The interesting part is, the audio file itself does not appear to be in the file system, so it is likely not being successfully downloaded from BB.

**Comment by mitchazj** [comment]
Thanks mate!
What's the extension code of the file? .mp3? .wav?

**Comment by Wade-Jensen** [comment]
.wav

**Comment by mitchazj** [comment]
Fixed in a recent commit.
